### PR TITLE
Setup a basic backend

### PR DESCRIPTION
**Pull request by R-Layer**
In this PR is still missing Kubernetes stuff but node and mongo are ready ( once the .env file has been created)

### CODE REVIEW

**Comment by itaisteinherz** [comment]
@R-Layer It would be great if you could add the server container directly to the branch instead of adding a submodule (this makes it easier to review the PR and iterate).

**Comment by itaisteinherz** [comment]
I've improved the code a bit and added [XO](https://github.com/xojs/xo) for linting in c9d42328f847f81e4f1118efa664a51a7a43bbbd.

This looks great, and I think there's only one thing missing: the `User` model needs to have a `name` property (a regular string).

I'll create tasks for implementing and documenting the models of the other data structures (Posts and Tags) on Trello.

**Comment by R-Layer** [comment]
Oh yeah, among the other things i should definitely setup the linter in my env. 

A question on the review:
 - I saw the env vars are being taken off the flow: is that just a shortcut to run the actual code or is it intentional to avoid it?

**Comment by itaisteinherz** [comment]
> I saw the env vars are being taken off the flow: is that just a shortcut to run the actual code or is it intentional to avoid it?

I’ve done it to simplify things, since we currently only use one environment variable - the port for the server to listen on, which also needs to be synchronized with the Docker configuration.

**Comment by itaisteinherz** [comment]
> I saw the env vars are being taken off the flow: is that just a shortcut to run the actual code or is it intentional to avoid it?

I’ve done it to simplify things, since we currently only use one environment variable - the port for the server to listen on, which also needs to be

**Comment by itaisteinherz** [comment]
@R-Layer It would be great if you could add the Post model in a separate PR, and remove it from this one.

**Comment by itaisteinherz** [comment]
Closing in favor of #12.

**Pull request closed without merging**
