### PR TITLE
Enable users to use tags for searching questions

### PR DESCRIPTION
**Pull request by R-Layer**
Add the tag component on the front as a select component from and design.
Add few tag to pre-populated questions.
Has to be optimized ad bug fixed more (a lot of unexpected edge cases! ),  the basic functionality is working though.

### CODE REVIEW

**Review by itaisteinherz — CHANGES_REQUESTED** [review]
This looks good except for a few things that still need to be fixed:

- When a user types out some text in the tag search field, we should only allow them to select tags they haven't selected yet.
- When users type out something in the tag search that isn't a tag, they shouldn't be allowed to select it. I was able to achieve this by changing the `Search` component's `mode` prop to be `"multiple"`, however that caused the `onChange` listener to never be called for some reason.
- When a user types out text, we should fetch about 5 tags from the server that are related/match what they've typed.
- After searching for a query, in case the query gets changed but not _completely_ rewritten, the selected tags list shouldn't be updated since if it does get updated, you can't change the tags sometimes without modifying the freetext query as well.

**Comment by R-Layer** [comment]
Ok, i made few changes: it should be consistent with what you pointed out, give it a check^^
One thing though: the (max) five tags displayed when you write /select are still not fetched from the server, they are filtered out from the tag state^^
Let me know if it's fine for you!

**Comment by itaisteinherz** [comment]
> the (max) five tags displayed when you write /select are still not fetched from the server, they are filtered out from the tag state^^

That's not the desirable behavior (in my opinion) since we will probably have hundreds of tags, and so prefetching the entire tag list and then searching it won't be very fast and efficient performance-wise, and will also mean doing large database queries.

**Comment by itaisteinherz** [comment]
@R-Layer I've implemented what I was talking about in d50133211e3d5ec1ca4923f00072e21bef1ce112.

**Review by itaisteinherz — APPROVED** [review]
@R-Layer Awesome work on this 🔥

**Pull request merged**
