### PR TITLE
Add a basic React frontend

### PR DESCRIPTION
**Pull request by itaisteinherz**
I've created a basic React frontend for the project using [Create React App](https://github.com/facebook/create-react-app).

### CODE REVIEW

**Review by mastas3 — DISMISSED** [review]
Looking good 😎

**Comment by geokeloglou** [comment]
Cool

**Review by geokeloglou — APPROVED** [review]
Cool

**Comment by itaisteinherz** [comment]
[Create a basic, working React app [30 minutes]](https://trello.com/c/KM6b7RSJ/1-create-a-basic-working-react-app-30-minutes)

**Pull request merged**
